language: php

sudo: false
dist: trusty
os: linux

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

matrix:
    include:
        - php: 7.1
          if: (type == push AND fork = false) OR (type == pull_request AND forke = true)
          env:
            - PHPUNIT_CONF=phpunit.xml.dist
        - php: 7.2
          if: (type == push AND fork = false) OR (type == pull_request AND forke = true)
          env:
            - PHPUNIT_CONF=phpunit_parameter.xml.dist
        - php: 7.2
          if: (type == push AND fork = false) OR (type == pull_request AND forke = true)
          env:
            - PHPUNIT_CONF=phpunit_subdomain.xml.dist
        - php: 7.2
          if: type == push AND branch = master AND fork = false
          env:
            - PHPUNIT_CONF=phpunit.xml.dist
            - COVERAGE_FILTER=UniteCMS\\CoreBundle\\Tests
        - php: 7.2
          if: type == push AND branch = master AND fork = false
          env:
            - PHPUNIT_CONF=phpunit.xml.dist
            - COVERAGE_FILTER=UniteCMS\\(CollectionField|Registration|Storage|VariantsField|WysiwygField)Bundle\\Tests

    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

services:
  - mysql

before_install:
  - |
    if ! [[ $COVERAGE_FILTER ]]; then
      phpenv config-rm xdebug.ini
    fi
  - composer self-update
  - mysql -e 'CREATE DATABASE unite_test;'
  - cp .env.dist .env

install:
  - composer install

before_script:
  - |
    if [[ $COVERAGE_FILTER ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi

script:
  - |
    if [[ $COVERAGE_FILTER ]]; then
        phpunit --filter '$coverage_filter' --configuration $PHPUNIT_CONF --coverage-clover clover.xml
    else
      phpunit --configuration $PHPUNIT_CONF
    fi

after_success:
  - |
    if [[ $COVERAGE_FILTER ]]; then
      ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
    fi